version: '3'
services:
  backend:
    build: .
    ports:
    - 12345:9000
    volumes:
    - ./backend-scala:/home/lwolski/projekt/sklep-play/
    working_dir: /home/lwolski/projekt/sklep-play/
    command: bash -c "source /home/lwolski/.sdkman/bin/sdkman-init.sh && sbt run"
  frontend:
    build: .
    ports:
    - 12346:3000
    volumes:
    - .:/home/lwolski/projekt/sklep-react/
    working_dir: /home/lwolski/projekt/sklep-react/
    command: bash -c "npm start"