version: '3'
services:
  backend:
    build: .
    ports:
    - "9000:9000"
    volumes:
    - ./backend-scala:/home/lwolski/projekt/sklep-play/
    working_dir: /home/lwolski/projekt/sklep-play/
    command: bash -c "source /home/lwolski/.sdkman/bin/sdkman-init.sh && sbt run"
  frontend:
    build: .
    ports:
    - 3000:3000
    volumes:
    - ./frontend-react:/home/lwolski/projekt/sklep-react/
    working_dir: /home/lwolski/projekt/sklep-react/
    command: bash -c "npm install && npm start"